process {

   withLabel: duckdb_tools {
      container = 'docker://quay.io/kfkf33/duckdb_env:v24.01.1'
  }
   withLabel: qtlmap_tools {
      container = 'docker://quay.io/eqtlcatalogue/qtlmap:v20.05.1'
  }

   withLabel: qtltools {
      container = 'docker://quay.io/eqtlcatalogue/qtltools:v22.03.1'
  }
   withLabel: susier {
      container = 'docker://quay.io/kfkf33/susier:v24.01.2'
  }
   withLabel: susie_finemapping {
      container = 'docker://quay.io/eqtlcatalogue/susie-finemapping:v20.08.1'
  }
}